Adding a section about calibration check
MewsSystems/org pull request #31
Opened 2022-10-02 19:48 UTC by susilm

2022-10-03 20:44 UTC, siroky requested changes
Actually, I think the calibration is becoming a bigger topic that would deserve its own section. Because it's another process and cadence we're doing and we should even embed it into the calendar:
- month before performance reviews, there should be pre-calibration session
- month before performance reviews, there should be the training/workshop for managers after pre-calibration session
- month after performance reviews, the should be the post-calibration session.
- optionally, month after performance reviews, there should be retrospective with managers

So my proposal is to create a new chapter in the career framework `10. Calibration`. Describe the initiatives there (pre calibration, training, post-calibration, retrospective). Embed it into the calendar as well. And refer to it from this guide as a reminder - e.g. that manager should ensure before doing perf. review that they participate/watch the training. 2nd level managers should perform pre-calibration session and inform their teams.

![image](https://user-images.githubusercontent.com/435787/193677887-3638559e-397c-4105-9af5-58a88bfd58be.png)

2022-10-03 20:44 UTC, siroky commented on tech/career-framework/performance-reviews.md
> +- Add latest performance review results to `Reviews` sheet in the tech-wide payroll file. This sheet contains historical ratings so it's a data source that can be used to understand the 'delta' (chan
I think this shouldn't be responsibility of family leads but rather of the person who prepares the calibration report - to make the snapshot. But ideally, there shouldn't be such need and the sheet should calculate it automatically, I just didn't get to it 😅

2022-10-03 20:44 UTC, siroky commented on tech/career-framework/performance-reviews.md
> +- Identify `calibration groups` that you want to look into - calibration group is a combination of a grade (e.g. `IC3` or `IC4`) and a track (e.g. `Engineer`). It doesn't make sense to compare career
Isn't calibration group of each person clear? That's given by their track and grade so I guess there's no work there.

2022-10-03 20:44 UTC, siroky commented on tech/career-framework/performance-reviews.md
> +### Consistency Checks (Calibration)
Maybe it would be best to split this to two parts:

- One should be describing how do we create the calibration report and what it consists of. That can be used as a documentation for the person who will be facilitating that. That's not too relevant for anyone else so I'd put it on the bottom.
- More important section should be here, under Second Level Managers, describing what to look for in the calibration report, how to interpret it, what should be the questions they should seek answers for. Kindof the last 3 points in this section, but I'd maybe describe the types of anomalies in more detail. Ideally, structure of the calibration report should be driven by these "use cases" and it should highlight the anomalies automatically.

2022-11-11 13:38 UTC, susilm commented on tech/career-framework/performance-reviews.md
> +- Identify `calibration groups` that you want to look into - calibration group is a combination of a grade (e.g. `IC3` or `IC4`) and a track (e.g. `Engineer`). It doesn't make sense to compare career
I rephrased this a little in context of other changes. But the point was that I want to explain what `calibration group` term means as we are using this term in the subsequent sentences.

2022-11-11 13:45 UTC, susilm commented on tech/career-framework/performance-reviews.md
> +- Add latest performance review results to `Reviews` sheet in the tech-wide payroll file. This sheet contains historical ratings so it's a data source that can be used to understand the 'delta' (chan
This was in the end rephrased in context of larger changes. But also, details about Mews-specific implementation of spreadsheet probably shouldn't be included in this framework.

2022-11-11 13:52 UTC, susilm commented
Uploading new version based on discussions during performance process workshops with other managers and directors. Some highlights:
* introducing calibration event during the performance review cycle - managers propose ratings and there is a calibration meeting to bless the proposed score before it gets communicated to employees. It prolongs the process a bit but should be worth it.  see `calibration.md` for details
* I didn't want to overcomplicate calendar so I rather added initial draft of timeline to describe "what happens within each performance review cycle". Eventually we can extend it and also share more visual version with specific dates for each ritual before reach review cycle.

2022-11-21 15:21 UTC, siroky requested changes
In terms of contents, LGTM. I suggest to polish the calibration file a bit before merging. There are few formatting issues (missing dots at the ends of sentences, broken lists) and maybe several grammatical issues, so let's iron that out e.g. using Grammarly.

2022-11-21 15:21 UTC, siroky commented on tech/career-framework/calibration.md
> +- Calibration sessions trainings for Managers
The wording seems confusing - I'd use either "calibration trainings" or "calibration sessions" but not "calibration sessions trainings".

2022-11-21 15:21 UTC, siroky commented on tech/career-framework/calibration.md
> +Having people aligned on expectations from each role up front is the most efficient way. We are going to have a sessions with managers before each performance review cycle to make sure everyone has t
... have a session or have sessions

2022-11-21 15:21 UTC, siroky commented on tech/career-framework/calibration.md
> +- Are we looking for these expectations as grow aspect or performance (role responsibility) aspect? Competencies once achieved are not guaranteed to be retained for ever
- Missing dot at the end of sentence.
- Not sure I understand "Are we looking for these expectations as grow aspect or performance (role responsibility) aspect?" maybe rewording would help or clarifying what "these expectations" refer to.

2022-11-21 15:21 UTC, siroky commented on tech/career-framework/calibration.md
> +- Employees fill in their self-rating in the competency spreadsheet and submit it to their manager AHEAD of the performance review meeting. Employees are encouraged to ask their colleagues for feedba
This should be reflected in the performance review process somewhere around here: https://github.com/MewsSystems/org/pull/31/files#diff-4ed7da08b1010b2a67cf6b15a8300df8bfd2ae07d7d7f00b625672f656b15df8R5

2022-11-21 15:21 UTC, siroky commented on tech/career-framework/calibration.md
> +
This blank line IMHO breaks formatting

2022-11-21 15:21 UTC, siroky commented on tech/career-framework/readme.md
> +| Duration  | Activity |
I'd update this timeline to be clear on what happens when. We have 2 months for performance reviews, so let's treat it as 8 weeks. And let's organize this according to what happens on which week, so that we can have clear timeline with deadlines and milestones. E.g. something like this:

- week 1 - manager training
- week 2-3 - self evaluation
- week 2-3 - manager evaluation
- week 4 - calibration session
- week 5-8 - review meetings
- week 7-8 - HR updates
- week 8 - ...

2022-11-22 22:13 UTC, susilm commented on tech/career-framework/calibration.md
> +- Calibration sessions trainings for Managers
makes sense. I've changed it for `Calibration Trainings`

2022-11-22 22:14 UTC, susilm commented on tech/career-framework/calibration.md
> +- Are we looking for these expectations as grow aspect or performance (role responsibility) aspect? Competencies once achieved are not guaranteed to be retained for ever
Rephrased, hopefully it makes more sense now.

2022-11-22 22:15 UTC, susilm commented on tech/career-framework/readme.md
> +| Duration  | Activity |
Good point, I've changed the format.

2022-11-22 22:25 UTC, susilm commented on tech/career-framework/calibration.md
> +- Employees fill in their self-rating in the competency spreadsheet and submit it to their manager AHEAD of the performance review meeting. Employees are encouraged to ask their colleagues for feedba
Not sure where exactly you are recommending to have more info about it. Could you point me to a specific document/chapter please?

2022-11-22 22:28 UTC, siroky commented on tech/career-framework/calibration.md
> +- Employees fill in their self-rating in the competency spreadsheet and submit it to their manager AHEAD of the performance review meeting. Employees are encouraged to ask their colleagues for feedba
I'll be doing some further updates, e.g. related to the technical leadership involvement we discussed on Monday after this is merged so I'll tackle it as part of that. Basically I plan to go through the whole framework and interlink it / reference it where it makes sense.

2022-11-24 22:44 UTC, siroky approved these changes

2022-11-24 22:44 UTC, merged